### ISSUE TITLE
Why is there no YOLO in the comparative experiment？

### ISSUE THREAD

**Issue by heha102** [Ryoo72/UNA#1]
Dear author，I just started learning about noise labeling problems. And my knowledge in this field is limited.  I want to ask why is there no YOLO in the comparative experiment? And YOLO is also rarely seen in other noise label detection papers. I will be grateful if the author can tell me why.

**Comment by Ryoo72** [comment]
It is likely that YOLO was not included because it uses a different setup, including the Darknet backbone, which makes fair comparison with other models challenging. Instead, we analyzed FCOS as a one-stage model. The reason other papers also do not use YOLO might be due to the lack of a suitable implementation in MMDetection. If you have any other questions, feel free to ask.
